In [626]:
#Importing all the necessary modules 
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, matthews_corrcoef
from sklearn.feature_extraction.text import CountVectorizer
import spacy
import joblib
from datetime import datetime, timedelta
import ipaddress
import time

In [627]:
nlp = spacy.load("en_core_web_sm")

In [628]:
#df = pd.read_csv('/content/drive/MyDrive/training_data.csv')
df = pd.read_csv('/content/drive/MyDrive/labeled_email_data25.csv')

In [629]:
#Defining all the features which are used in the model
def extract_username(email):
    return email.split('@')[0]

In [630]:
def extract_domain(email):
    return email.split('@')[-1]

In [631]:
def generate_ngrams(text, n_range=(3, 6)):
    ngrams = []
    length = len(text)
    for n in range(n_range[0], min(n_range[1]+1, length+1)):
        ngrams.extend([text[i:i+n] for i in range(length-n+1)])
    return ngrams

In [632]:
def contains_person_name_from_ngrams(ngrams):
    for token in ngrams:
        doc = nlp(token)
        for ent in doc.ents:
            if ent.label_ == 'PERSON':
                return 1  # Mark as true if a PERSON entity is found
    return 0

In [562]:
def is_valid_ip(ip):
    try:
        ipaddress.ip_address(ip)
        return 1  # IP is valid
    except ValueError:
        return 0

,email,length_of_username,num_special_chars,has_person_name_ngram,label
0,bohdan.ravlyk.mbdpts.2023@lpnu.ua,25,3,1,0
1,axel@nystruktur.no,4,0,0,0
2,raymond@sttinternational.nl,7,0,1,1
3,ray.flynn@turmec.com,9,1,1,1
4,davy.siroyt@aircoplus.be,11,1,1,1
5,marco.noordman@idagro.nl,14,1,1,1
6,ray.flynn@turmec.com,9,1,1,1
7,jeremybouhour@seti-14.fr,13,0,1,1
8,detailing.mark@conceptdg.com.au,14,1,1,1
9,simarhunjan214@gmail.com,14,0,1,1
10,dangtran461@gmail.com,11,0,1,1
11,nowabiala137@gmail.com,12,0,1,1
12,p2606.64430,11,1,0,0
13,gprosser@billington-structures.co.uk,8,0,0,0
14,dogan@artera.be,5,0,0,0
15,ray.flynn@turmec.com,9,1,1,1
16,marahim1@systra.info,8,0,1,1
17,danghuynh0313@gmail.com,13,0,1,1
18,muhdsyafiq.ara@gmail.com,14,1,1,1
19,assembleur.trimble@sottas.ch,18,1,1,1

In [633]:
def extract_features_with_person_check(email,ip):
    username = extract_username(email)
    length_of_username = len(username)
    num_special_chars = sum(not char.isalnum() for char in username)
    digits_to_letters_ratio = sum(char.isdigit() for char in username) / (sum(char.isalpha() for char in username) + 1)
    consecutive_chars = sum(username[i] == username[i+1] for i in range(len(username)-1))

    # Generate n-grams and check if any are identified as a PERSON
    ngrams = generate_ngrams(username, n_range=(3, 6))
    has_person_name_ngram = contains_person_name_from_ngrams(ngrams)


    #ip address
    ip_valid = is_valid_ip(ip)


    return [length_of_username, num_special_chars, digits_to_letters_ratio, consecutive_chars, has_person_name_ngram , ip_valid]

In [634]:
y = df['label'].values

In [635]:
basic_features = np.array([extract_features_with_person_check(email, ip) for email, ip in zip(df['user_id'], df['source_ip'])])

In [636]:
#Training the model
X_train, X_test, y_train, y_test = train_test_split(basic_features, y, test_size=0.2, random_state=42)

In [637]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

,email,length_of_username,num_special_chars,has_person_name_ngram,label
0,bohdan.ravlyk.mbdpts.2023@lpnu.ua,25,3,1,0
1,axel@nystruktur.no,4,0,0,0
2,raymond@sttinternational.nl,7,0,1,1
3,ray.flynn@turmec.com,9,1,1,1
4,davy.siroyt@aircoplus.be,11,1,1,1

In [638]:
def contains_edu_or_org(email):
    domain = extract_domain(email)
    return 1 if 'edu' in domain or 'org' in domain else 0

NoNameservers: All nameservers failed to answer the query lpnu.ua. IN MX: Server Do53:10.40.53.23@53 answered [Errno 51] Network is unreachable; Server Do53:10.40.53.28@53 answered [Errno 51] Network is unreachable

In [155]:
def predict_with_domain_check(X, emails, ips, model):
    predictions = []
    for features, email, ip in zip(X, emails, ips):
        if ',' in ip:
            predictions.append(0)
            continue

        domain = extract_domain(email)
        if 'edu' in domain or 'org' in domain:
            predictions.append(1)
        else:
            prediction = model.predict(features.reshape(1, -1))
            predictions.append(prediction[0])

    return predictions

In [81]:
df_unlabeled = pd.read_csv('/content/drive/MyDrive/search-results-2024-11-26T21_42_11.430-0800.csv')
len(df_unlabeled)

In [82]:
basic_features_unlabeled = np.array([extract_features_with_person_check(email, ip) for email, ip in zip(df_unlabeled['user_id'], df_unlabeled['source_ip'])])
basic_features_unlabeled

In [416]:
unlabeled_predictions = predict_with_domain_check(basic_features_unlabeled, df_unlabeled['user_id'], df_unlabeled['source_ip'], model)

In [569]:
df_unlabeled['Predicted_Label'] = unlabeled_predictions
df_unlabeled.head(100)

In [570]:
df_unlabeled.to_csv('output.csv', index=False)

In [571]:
df_unlabeled['Predicted_Label'].value_counts()

LogisticRegression(max_iter=1000)